---
### Install samba in a container

- name: Create samba container
  docker_container:
    name: "{{ name }}"
    image: strm/samba
    state: started
    restart_policy: "unless-stopped"
    volumes: "{{ volumes }}"
    env: "{{ env }}"
    published_ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:455
      - 445:445/udp
